<?php // vim:ts=4:sw=4:et:fdm=marker

namespace atk4\dsql;

/**
 * All exceptions generated by DSQL will
 */
class Exception extends \Exception
{
    /**
     * Most exceptions would be a cause by some other exception, DSQL
     * will encapsulate them and allow you to access them anyway.
     */
    // TODO: think if this is actually needed.
    // function getOriginal();
}
